name: Convert MISP playbooks to HTML

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  convert-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert Jupyter notebooks to HTML
      run: |
        mkdir -p html-notebooks
        find misp-playbooks -name "*.ipynb" -exec jupyter nbconvert --to html --output-dir=html-notebooks {} +

    - name: Update README references
      run: |
        README_FILE="README.md"
        if [ -f "$README_FILE" ]; then
          sed -i 's|\(misp-playbooks/.*\)\.ipynb|\1.html|g' "$README_FILE"
        fi

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        cp -r html-notebooks/* misp-playbooks/
        git add misp-playbooks/*.html README.md
        git commit -m "Auto-convert notebooks to HTML and update README"
        git push
